name: Publish Release
on: 
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install setuptools
        run: |
          pip install --upgrade setuptools
      - name: Install wheel
        run: |
          pip install wheel
      - name: Install twine
        run: |
          pip install twine
      - name: Build and publish
        env:
          STACKMANAGER_VERSION: ${{ github.event.release.tag_name }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: '${{ secrets.PYPI_token }}'
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
